version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/budget
      - JWT_SECRET=a_dummy_jwt_secret_by_sebxp
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"